stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 121.40.49.87:5000/docker-demo
      pushRemote: true
      registry: 121.40.49.87:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./demo_k8s_deploy.yaml
timeout: 60
notification: {}
