apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
  - name: maven
    port: 8889
    nodePort: 31002
    targetPort: 8888
    protocol: TCP
  selector:
    app: maven
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  selector:
    matchLabels:
      app: maven
  replicas: 1
  template:
    metadata:
      labels:
        app: maven
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: maven
          image: 121.40.49.87:5000/docker-demo:latest
          ports:
          - containerPort: 8888
          env:
            - name: key
              value: "value"
