apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
  - name: maven
    port: 8889
    nodePort: 31002
    targetPort: 8888
    protocol: TCP
  selector:
    app: maven
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  selector:
    matchLabels:
      app: maven
  replicas: 1
  template:
    metadata:
      labels:
        app: maven
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: maven
          image: 118.31.22.147:5000/docker-demo:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
          - containerPort: 8888
          env:
            - name: RUN_ARGS
              value: "--spring.profiles.active=qa"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: www.dreambuilder.store
      http:
        paths:
          - path: /
            backend:
              serviceName: maven-service
              servicePort: 8889