apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  type: NodePort
  ports:
  - name: maven
    port: 3306
    nodePort: 32006
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: sql-data
      volumes:
        - name: sql-data
          hostPath:
            path: /home/mysql/data
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql-ingress
  namespace: mysql
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: mysql.dreambuilder.store
      http:
        paths:
          - path: /
            backend:
              serviceName: mysql-service
              servicePort: 3306