logging.config: classpath:logback-spring.xml
env: default

server:
  port: 8888

management:
  endpoints:
    web:
      exposure.include: "*"

spring:
  application:
    name: docker-demo
  profiles:
    active: local